---
title: Photography Submissions
author: ''
date: '2022-10-28'
slug: []
categories: []
weight: 1
tags: []
description: ~
draft: false
layout: standard
show_title_as_headline: true
---


```{r echo=FALSE, message=FALSE, warning=FALSE, include=F}
library(googlesheets4)
gs4_auth(email = "scaf2k22@gmail.com")
library(htmlwidgets)
library(slickR)
library(tidyverse)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}

x <- read_sheet("https://docs.google.com/spreadsheets/d/1pICSEmyqTJ1y-93B5VuTYQp-C_CRTVK-m-8TfVPr0so/edit?usp=sharing")

x <- x %>% filter(type == "photo")


slickR(obj = x$url, height = 400, width = "95%") %synch%
( slickR(x$name, slideType = 'p') + settings(arrows = FALSE) )

# fs::dir_create(here::here("static", "carousel"))
# fs::dir_create(here::here("data", "rds_files"))
# 
# file_names <- fs::path_file(x$url)
#   
# dest_names <- here::here("static", "carousel", file_names)
# 
# map2(x$url, dest_names, download.file, method = "curl")
# 
# x$url %>% write_rds(here::here('data', 'rds_files', 'url.rds'))
# x$name %>% write_rds(here::here('data', 'rds_files', 'name.rds'))
# dest_names %>% write_rds(here::here("data", "rds_files", 'dest_names.rds'))
# photographer_names %>% write_rds(here::here("data", "rds_files", 'photographer_names.rds'))
  
```


```{r echo=FALSE}
# url <- readr::read_rds(here::here("data", "rds_files", 'url.rds'))
# name <- readr::read_rds(here::here("data", "rds_files", 'name.rds'))
# dest_names <- readr::read_rds(here::here("data", "rds_files", 'dest_names.rds'))
# photographer_names <- readr::read_rds(here::here("data", "rds_files", 'photographer_names.rds'))

```

